apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testnet-casperholders-cert
spec:
  secretName: testnet-casperholders-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: testnet.casperholders.io
  dnsNames:
    - testnet.casperholders.io