apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: casperholders-cert
spec:
  secretName: casperholders-cert
  issuerRef:
    name: letsencrypt-prod
  commonName: casperholders.io
  dnsNames:
    - casperholders.io