apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: casperholders-cert
spec:
  secretName: casperholders-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: casperholders.io
  dnsNames:
    - casperholders.io
    - www.casperholders.io